name: deployment_pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy to flyio
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Discord notification success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'push' && success() }}
        with:
          severity: info
          details: Build success. Check out https://pokedex-yingtu.fly.dev/
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord notification failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'push' && failure() }}
        with:
          severity: info
          details: Build failure. See Commit URL for more details
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord notification canceled
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'push' && cancelled() }}
        with:
          severity: info
          details: Build cancelled.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: list all folders
        run: ls -la
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
